export * from './pagination/index'
// import Preview from './preview/index'
export * from './layout/index'
// import Autocomplete from './autocomplete/index'
// import Dropdown from './dropdown/index'
// import DropdownMenu from './dropdown-menu/index'
// import DropdownItem from './dropdown-item/index'
export * from './menu/index'
// import Submenu from './submenu/index'
// import MenuItem from './menu-item/index'
// import MenuItemGroup from './menu-item-group/index'
export * from './input/index'
// import InputNumber from './input-number/index'
export * from './radio/index'
export * from './radio-group/index'
export * from './radio-button/index'
export * from './checkbox/index'
// import CheckboxButton from './checkbox-button/index'
// import CheckboxGroup from './checkbox-group/index'
export * from './switch/index'
export * from './select/index'
export * from './option/index'
// import OptionGroup from './option-group/index'
export * from './button/index'
// import ButtonGroup from './button-group/index'
export * from './search/index'
export * from './dialog/index'
// import Modal from './modal/index'
// import CommonForm from './common-form/index'
export * from './table/index'
export * from './table-pagination/index'
export * from './table-operation/index'
// import TableColumn from './table-column/index'
// import DatePicker from './date-picker/index'
export * from './time-select/index'
export * from './time-picker/index'
// import Popover from './popover/index'
export * from './tooltip/index'
// import MessageBox from './message-box/index'
// import Breadcrumb from './breadcrumb/index'
// import BreadcrumbItem from './breadcrumb-item/index'
export * from './form/index'
export * from './form-item/index'
export * from './form-search/index'
export * from './form-view/index'
// import Tabs from './tabs/index'
// import TabPane from './tab-pane/index'
export * from './tag/index'
export * from './tree/index'
export * from './alert/index'
export * from './notification/index'
export * from './slider/index'
// import Loading from './loading/index'
// import Icon from './icon/index'
// import Row from './row/index'
// import Col from './col/index'
export * from './upload/index'
// import Progress from './progress/index'
// import Spinner from './spinner/index'
// import Message from './message/index'
// import Badge from './badge/index'
export * from './card/index'
// import Rate from './rate/index'
// import Steps from './steps/index'
// import Step from './step/index'
// import Carousel from './carousel/index'
// import Scrollbar from './scrollbar/index'
// import CarouselItem from './carousel-item/index'
// import Collapse from './collapse/index'
// import CollapseItem from './collapse-item/index'
export * from './cascader/index'
// import ColorPicker from './color-picker/index'
// import Transfer from './transfer/index'
// import Container from './container/index'
// import Header from './header/index'
// import Aside from './aside/index'
// import Main from './main/index'
// import Footer from './footer/index'
// import Timeline from './timeline/index'
// import TimelineItem from './timeline-item/index'
// import Link from './link/index'
// import Divider from './divider/index'
// import Image from './image/index'
// import Calendar from './calendar/index'
// import Backtop from './backtop/index'
// import InfiniteScroll from './infinite-scroll/index'
// import PageHeader from './page-header/index'
export * from './cascader-panel/index'
// import Avatar from './avatar/index'
// import Drawer from './drawer/index'
// import Statistic from './statistic/index'
// import Popconfirm from './popconfirm/index'
// import Skeleton from './skeleton/index'
// import SkeletonItem from './skeleton-item/index'
// import Empty from './empty/index'
// import Descriptions from './descriptions/index'
// import DescriptionsItem from './descriptions-item/index'
// import Result from './result/index'

//   Vue.use(InfiniteScroll)
//   Vue.use(Loading.directive)

//   Vue.prototype.$ELEMENT = {
//     size: opts.size || '',
//     zIndex: opts.zIndex || 2000
//   }

//   Vue.prototype.$loading = Loading.service
//   Vue.prototype.$msgbox = MessageBox
//   Vue.prototype.$alert = MessageBox.alert
//   Vue.prototype.$confirm = MessageBox.confirm
//   Vue.prototype.$prompt = MessageBox.prompt
// Vue.prototype.$notify = WebNotification
//   Vue.prototype.$message = Message
