export default {
  '/src/': [
    {
      text: 'element二次封装',
      items: [
        { text: 'Alert', link: '/src/my-alert/index' },
        { text: 'Button', link: '/src/my-button/index' },
        { text: 'Card', link: '/src/my-card/index' },
        { text: 'Dialog', link: '/src/my-dialog/index' },
        { text: 'DatePicker', link: '/src/my-date-picker/index' },
        { text: 'Menu', link: '/src/my-menu/index' },
        { text: 'HeaderBreadcrumb', link: '/src/my-header-breadcrumb/index' },
        { text: 'Message', link: '/src/my-message/index' },
        { text: 'MessageBox', link: '/src/my-message-box/index' },
        { text: 'Notification', link: '/src/my-notification/index' },
        { text: 'PageContainer', link: '/src/my-page-container/index' },
        { text: 'Pagination', link: '/src/my-pagination/index' },
        { text: 'Radio', link: '/src/my-radio/index' },
        { text: 'Select', link: '/src/my-select/index' },
        { text: 'Steps', link: '/src/my-steps/index' },
        { text: 'Switch', link: '/src/my-switch/index' },
        { text: 'Table', link: '/src/my-table/index' },
        { text: 'Tabs', link: '/src/my-tabs/index' },
        { text: 'Checkbox', link: '/src/my-checkbox/index' },
        { text: 'Link', link: '/src/my-link/index' },
      ]
    }
  ],
  '/element/': [
    {
      text: "base",
      items: [
        // { text: "index", link: "/element/base/" },
        { text: "layout", link: "/element/base/layout" },
        { text: "container", link: "/element/base/container" },
        { text: "button", link: "/element/base/button" },
        { text: "link", link: "/element/base/link" },
        { text: "space", link: "/element/base/space" },
        { text: "scrollbar", link: "/element/base/scrollbar" },
        { text: "config-provider", link: "/element/base/config-provider" },
      ],
    },
    {
      text: "form",
      items: [
        // { text: "index", link: "/element/form/" },
        { text: "layout", link: "/element/form/cascader" },
        { text: "container", link: "/element/form/radio" },
        { text: "button", link: "/element/form/checkbox" },
        { text: "link", link: "/element/form/input" },
        { text: "space", link: "/element/form/inputnumber" },
        { text: "scrollbar", link: "/element/form/select" },
        { text: "config-provider", link: "/element/form/selectv2" },
        { text: "index", link: "/element/form/switch" },
        { text: "layout", link: "/element/form/slider" },
        { text: "container", link: "/element/form/timepicker" },
        { text: "button", link: "/element/form/timeselect" },
        { text: "link", link: "/element/form/datepicker" },
        { text: "space", link: "/element/form/datetimepicker" },
        { text: "scrollbar", link: "/element/form/upload" },
        { text: "config-provider", link: "/element/form/rate" },
        { text: "space", link: "/element/form/colorpicker" },
        { text: "scrollbar", link: "/element/form/transfer" },
        { text: "config-provider", link: "/element/form/form" },
      ],
    },
    {
      text: "data",
      items: [
        // { text: "index", link: "/element/data/" },
        { text: "layout", link: "/element/data/table" },
        { text: "container", link: "/element/data/tag" },
        { text: "button", link: "/element/data/progress" },
        { text: "link", link: "/element/data/tree" },
        { text: "space", link: "/element/data/pagination" },
        { text: "scrollbar", link: "/element/data/badge" },
        { text: "config-provider", link: "/element/data/avatar" },
        { text: "link", link: "/element/data/skeleton" },
        { text: "space", link: "/element/data/empty" },
        { text: "scrollbar", link: "/element/data/descriptions" },
        { text: "config-provider", link: "/element/data/result" },
      ],
    },
    {
      text: "notice",
      items: [
        // { text: "index", link: "/element/notice/" },
        { text: "layout", link: "/element/notice/alert" },
        { text: "container", link: "/element/notice/loading" },
        { text: "button", link: "/element/notice/message" },
        { text: "link", link: "/element/notice/messagebox" },
        { text: "space", link: "/element/notice/notification" },
      ],
    },
    {
      text: "navigation",
      items: [
        // { text: "index", link: "/element/navigation/" },
        { text: "layout", link: "/element/navigation/affix" },
        { text: "container", link: "/element/navigation/navmenu" },
        { text: "button", link: "/element/navigation/tabs" },
        { text: "link", link: "/element/navigation/breadcrumb" },
        { text: "space", link: "/element/navigation/pageheader" },
        { text: "scrollbar", link: "/element/navigation/dropdown" },
        { text: "config-provider", link: "/element/navigation/steps" },
      ],
    },
    {
      text: "others",
      items: [
        // { text: "index", link: "/element/others/" },
        { text: "layout", link: "/element/others/dialog" },
        { text: "container", link: "/element/others/tooltip" },
        { text: "button", link: "/element/others/popover" },
        { text: "link", link: "/element/others/popconfirm" },
        { text: "space", link: "/element/others/card" },
        { text: "scrollbar", link: "/element/others/carousel" },
        { text: "config-provider", link: "/element/others/collapse" },
        { text: "layout", link: "/element/others/timeline" },
        { text: "container", link: "/element/others/drawer" },
        { text: "button", link: "/element/others/divider" },
        { text: "link", link: "/element/others/calendar-calendar" },
        { text: "space", link: "/element/others/image" },
        { text: "scrollbar", link: "/element/others/backtop" },
        { text: "config-provider", link: "/element/others/infinitescroll" },
      ],
    },
  ]
}