export default {
  '/src/element-plus/': [
    {
      text: "base",
      items: [
        // { text: "index", link: "/src/element-plus/base/" },
        { text: "layout", link: "/src/element-plus/base/layout" },
        { text: "container", link: "/src/element-plus/base/container" },
        { text: "button", link: "/src/element-plus/base/button" },
        { text: "link", link: "/src/element-plus/base/link" },
        { text: "space", link: "/src/element-plus/base/space" },
        { text: "scrollbar", link: "/src/element-plus/base/scrollbar" },
        { text: "config-provider", link: "/src/element-plus/base/config-provider" },
      ],
    },
    {
      text: "form",
      items: [
        // { text: "index", link: "/src/element-plus/form/" },
        { text: "layout", link: "/src/element-plus/form/cascader" },
        { text: "container", link: "/src/element-plus/form/radio" },
        { text: "button", link: "/src/element-plus/form/checkbox" },
        { text: "link", link: "/src/element-plus/form/input" },
        { text: "space", link: "/src/element-plus/form/inputnumber" },
        { text: "scrollbar", link: "/src/element-plus/form/select" },
        { text: "config-provider", link: "/src/element-plus/form/selectv2" },
        { text: "index", link: "/src/element-plus/form/switch" },
        { text: "layout", link: "/src/element-plus/form/slider" },
        { text: "container", link: "/src/element-plus/form/timepicker" },
        { text: "button", link: "/src/element-plus/form/timeselect" },
        { text: "link", link: "/src/element-plus/form/datepicker" },
        { text: "space", link: "/src/element-plus/form/datetimepicker" },
        { text: "scrollbar", link: "/src/element-plus/form/upload" },
        { text: "config-provider", link: "/src/element-plus/form/rate" },
        { text: "space", link: "/src/element-plus/form/colorpicker" },
        { text: "scrollbar", link: "/src/element-plus/form/transfer" },
        { text: "config-provider", link: "/src/element-plus/form/form" },
      ],
    },
    {
      text: "data",
      items: [
        // { text: "index", link: "/src/element-plus/data/" },
        { text: "layout", link: "/src/element-plus/data/table" },
        { text: "container", link: "/src/element-plus/data/tag" },
        { text: "button", link: "/src/element-plus/data/progress" },
        { text: "link", link: "/src/element-plus/data/tree" },
        { text: "space", link: "/src/element-plus/data/pagination" },
        { text: "scrollbar", link: "/src/element-plus/data/badge" },
        { text: "config-provider", link: "/src/element-plus/data/avatar" },
        { text: "link", link: "/src/element-plus/data/skeleton" },
        { text: "space", link: "/src/element-plus/data/empty" },
        { text: "scrollbar", link: "/src/element-plus/data/descriptions" },
        { text: "config-provider", link: "/src/element-plus/data/result" },
      ],
    },
    {
      text: "notice",
      items: [
        // { text: "index", link: "/src/element-plus/notice/" },
        { text: "layout", link: "/src/element-plus/notice/alert" },
        { text: "container", link: "/src/element-plus/notice/loading" },
        { text: "button", link: "/src/element-plus/notice/message" },
        { text: "link", link: "/src/element-plus/notice/messagebox" },
        { text: "space", link: "/src/element-plus/notice/notification" },
      ],
    },
    {
      text: "navigation",
      items: [
        // { text: "index", link: "/src/element-plus/navigation/" },
        { text: "layout", link: "/src/element-plus/navigation/affix" },
        { text: "container", link: "/src/element-plus/navigation/navmenu" },
        { text: "button", link: "/src/element-plus/navigation/tabs" },
        { text: "link", link: "/src/element-plus/navigation/breadcrumb" },
        { text: "space", link: "/src/element-plus/navigation/pageheader" },
        { text: "scrollbar", link: "/src/element-plus/navigation/dropdown" },
        { text: "config-provider", link: "/src/element-plus/navigation/steps" },
      ],
    },
    {
      text: "others",
      items: [
        // { text: "index", link: "/src/element-plus/others/" },
        { text: "layout", link: "/src/element-plus/others/dialog" },
        { text: "container", link: "/src/element-plus/others/tooltip" },
        { text: "button", link: "/src/element-plus/others/popover" },
        { text: "link", link: "/src/element-plus/others/popconfirm" },
        { text: "space", link: "/src/element-plus/others/card" },
        { text: "scrollbar", link: "/src/element-plus/others/carousel" },
        { text: "config-provider", link: "/src/element-plus/others/collapse" },
        { text: "layout", link: "/src/element-plus/others/timeline" },
        { text: "container", link: "/src/element-plus/others/drawer" },
        { text: "button", link: "/src/element-plus/others/divider" },
        { text: "link", link: "/src/element-plus/others/calendar-calendar" },
        { text: "space", link: "/src/element-plus/others/image" },
        { text: "scrollbar", link: "/src/element-plus/others/backtop" },
        { text: "config-provider", link: "/src/element-plus/others/infinitescroll" },
      ],
    },
  ],
  '/src/element-package/': [
    {
      text: "base",
      items: [
        // { text: "index", link: "/src/element-package/base/" },
        { text: "layout", link: "/src/element-package/base/layout" },
        { text: "container", link: "/src/element-package/base/container" },
        { text: "button", link: "/src/element-package/base/button" },
        { text: "link", link: "/src/element-package/base/link" },
        { text: "space", link: "/src/element-package/base/space" },
        { text: "scrollbar", link: "/src/element-package/base/scrollbar" },
        { text: "config-provider", link: "/src/element-package/base/config-provider" },
      ],
    },
    {
      text: "form",
      items: [
        // { text: "index", link: "/src/element-package/form/" },
        { text: "layout", link: "/src/element-package/form/cascader" },
        { text: "container", link: "/src/element-package/form/radio" },
        { text: "button", link: "/src/element-package/form/checkbox" },
        { text: "link", link: "/src/element-package/form/input" },
        { text: "space", link: "/src/element-package/form/inputnumber" },
        { text: "scrollbar", link: "/src/element-package/form/select" },
        { text: "config-provider", link: "/src/element-package/form/selectv2" },
        { text: "index", link: "/src/element-package/form/switch" },
        { text: "layout", link: "/src/element-package/form/slider" },
        { text: "container", link: "/src/element-package/form/timepicker" },
        { text: "button", link: "/src/element-package/form/timeselect" },
        { text: "link", link: "/src/element-package/form/datepicker" },
        { text: "space", link: "/src/element-package/form/datetimepicker" },
        { text: "scrollbar", link: "/src/element-package/form/upload" },
        { text: "config-provider", link: "/src/element-package/form/rate" },
        { text: "space", link: "/src/element-package/form/colorpicker" },
        { text: "scrollbar", link: "/src/element-package/form/transfer" },
        { text: "config-provider", link: "/src/element-package/form/form" },
      ],
    },
    {
      text: "data",
      items: [
        // { text: "index", link: "/src/element-package/data/" },
        { text: "layout", link: "/src/element-package/data/table" },
        { text: "container", link: "/src/element-package/data/tag" },
        { text: "button", link: "/src/element-package/data/progress" },
        { text: "link", link: "/src/element-package/data/tree" },
        { text: "space", link: "/src/element-package/data/pagination" },
        { text: "scrollbar", link: "/src/element-package/data/badge" },
        { text: "config-provider", link: "/src/element-package/data/avatar" },
        { text: "link", link: "/src/element-package/data/skeleton" },
        { text: "space", link: "/src/element-package/data/empty" },
        { text: "scrollbar", link: "/src/element-package/data/descriptions" },
        { text: "config-provider", link: "/src/element-package/data/result" },
      ],
    },
    {
      text: "notice",
      items: [
        // { text: "index", link: "/src/element-package/notice/" },
        { text: "layout", link: "/src/element-package/notice/alert" },
        { text: "container", link: "/src/element-package/notice/loading" },
        { text: "button", link: "/src/element-package/notice/message" },
        { text: "link", link: "/src/element-package/notice/messagebox" },
        { text: "space", link: "/src/element-package/notice/notification" },
      ],
    },
    {
      text: "navigation",
      items: [
        // { text: "index", link: "/src/element-package/navigation/" },
        { text: "layout", link: "/src/element-package/navigation/affix" },
        { text: "container", link: "/src/element-package/navigation/navmenu" },
        { text: "button", link: "/src/element-package/navigation/tabs" },
        { text: "link", link: "/src/element-package/navigation/breadcrumb" },
        { text: "space", link: "/src/element-package/navigation/pageheader" },
        { text: "scrollbar", link: "/src/element-package/navigation/dropdown" },
        { text: "config-provider", link: "/src/element-package/navigation/steps" },
      ],
    },
    {
      text: "others",
      items: [
        // { text: "index", link: "/src/element-package/others/" },
        { text: "layout", link: "/src/element-package/others/dialog" },
        { text: "container", link: "/src/element-package/others/tooltip" },
        { text: "button", link: "/src/element-package/others/popover" },
        { text: "link", link: "/src/element-package/others/popconfirm" },
        { text: "space", link: "/src/element-package/others/card" },
        { text: "scrollbar", link: "/src/element-package/others/carousel" },
        { text: "config-provider", link: "/src/element-package/others/collapse" },
        { text: "layout", link: "/src/element-package/others/timeline" },
        { text: "container", link: "/src/element-package/others/drawer" },
        { text: "button", link: "/src/element-package/others/divider" },
        { text: "link", link: "/src/element-package/others/calendar-calendar" },
        { text: "space", link: "/src/element-package/others/image" },
        { text: "scrollbar", link: "/src/element-package/others/backtop" },
        { text: "config-provider", link: "/src/element-package/others/infinitescroll" },
      ],
    },
  ]
}