export default {
  '/element-plus/base/': [
    {
      text: "base",
      items: [
        { text: "首页", link: "/element-plus/base/" },
        { text: "layout", link: "/element-plus/base/layout" },
        { text: "container", link: "/element-plus/base/container" },
        { text: "button", link: "/element-plus/base/button" },
        { text: "link", link: "/element-plus/base/link" },
        { text: "space", link: "/element-plus/base/space" },
        { text: "scrollbar", link: "/element-plus/base/scrollbar" },
        { text: "config-provider", link: "/element-plus/base/config-provider" },
      ],
    }
  ],
  '/element-plus/form/': [
    {
      text: "form",
      items: [
        { text: "首页", link: "/element-plus/form/" },
        { text: "一.cascader", link: "/element-plus/form/1.cascader" },
        { text: "二.checkbox", link: "/element-plus/form/2.checkbox" },
        { text: "三.input", link: "/element-plus/form/3.input" },
        { text: "四.inputnumber", link: "/element-plus/form/4.inputnumber" },
        { text: "五.select", link: "/element-plus/form/5.select" },
        { text: "六.selectv2", link: "/element-plus/form/6.selectv2" },
        { text: "七.radio", link: "/element-plus/form/7.radio" },
        { text: "八.switch", link: "/element-plus/form/8.switch" },
        { text: "九.slider", link: "/element-plus/form/9.slider" },
        { text: "十.timepicker", link: "/element-plus/form/10.timepicker" },
        { text: "十一.timeselect", link: "/element-plus/form/11.timeselect" },
        { text: "十二.datepicker", link: "/element-plus/form/12.datepicker" },
        { text: "十三.datetimepicker", link: "/element-plus/form/13.datetimepicker" },
        { text: "十四.upload", link: "/element-plus/form/14.upload" },
        { text: "十五.rate", link: "/element-plus/form/15.rate" },
        { text: "十六.ColorPicker", link: "/element-plus/form/16.colorpicker" },
        { text: "十七.Transfer", link: "/element-plus/form/17.transfer" },
        { text: "十八.Form", link: "/element-plus/form/18.form" },
      ],
    },
  ],
  '/element-plus/data/': [
    {
      text: "data",
      items: [
        { text: "首页", link: "/element-plus/data/" },
        { text: "table", link: "/element-plus/data/table" },
        { text: "tag", link: "/element-plus/data/tag" },
        { text: "progress", link: "/element-plus/data/progress" },
        { text: "tree", link: "/element-plus/data/tree" },
        { text: "pagination", link: "/element-plus/data/pagination" },
        { text: "badge", link: "/element-plus/data/badge" },
        { text: "avatar", link: "/element-plus/data/avatar" },
        { text: "skeleton", link: "/element-plus/data/skeleton" },
        { text: "empty", link: "/element-plus/data/empty" },
        { text: "descriptions", link: "/element-plus/data/descriptions" },
        { text: "result", link: "/element-plus/data/result" },
      ],
    },
  ],
  '/element-plus/notice/': [
    {
      text: "notice",
      items: [
        { text: "首页", link: "/element-plus/notice/" },
        { text: "alert", link: "/element-plus/notice/alert" },
        { text: "loading", link: "/element-plus/notice/loading" },
        { text: "message", link: "/element-plus/notice/message" },
        { text: "messagebox", link: "/element-plus/notice/messagebox" },
        { text: "notification", link: "/element-plus/notice/notification" },
      ],
    },
  ],
  '/element-plus/navigation/': [
    {
      text: "navigation",
      items: [
        { text: "首页", link: "/element-plus/navigation/" },
        { text: "affix", link: "/element-plus/navigation/affix" },
        { text: "navmenu", link: "/element-plus/navigation/navmenu" },
        { text: "tabs", link: "/element-plus/navigation/tabs" },
        { text: "breadcrumb", link: "/element-plus/navigation/breadcrumb" },
        { text: "pageheader", link: "/element-plus/navigation/pageheader" },
        { text: "dropdown", link: "/element-plus/navigation/dropdown" },
        { text: "steps", link: "/element-plus/navigation/steps" },
      ],
    }
  ],
  '/element-plus/others/': [
    {
      text: "others",
      items: [
        { text: "首页", link: "/element-plus/others/" },
        { text: "dialog", link: "/element-plus/others/dialog" },
        { text: "tooltip", link: "/element-plus/others/tooltip" },
        { text: "popover", link: "/element-plus/others/popover" },
        { text: "popconfirm", link: "/element-plus/others/popconfirm" },
        { text: "card", link: "/element-plus/others/card" },
        { text: "carousel", link: "/element-plus/others/carousel" },
        { text: "collapse", link: "/element-plus/others/collapse" },
        { text: "timeline", link: "/element-plus/others/timeline" },
        { text: "drawer", link: "/element-plus/others/drawer" },
        { text: "divider", link: "/element-plus/others/divider" },
        { text: "calendar-calendar", link: "/element-plus/others/calendar-calendar" },
        { text: "image", link: "/element-plus/others/image" },
        { text: "backtop", link: "/element-plus/others/backtop" },
        { text: "infinitescroll", link: "/element-plus/others/infinitescroll" },
      ],
    },
  ],
  '/element-package/base/': [
    {
      text: "base",
      items: [
        { text: "首页", link: "/element-package/base/" },
        { text: "layout", link: "/element-package/base/layout" },
        { text: "container", link: "/element-package/base/container" },
        { text: "button", link: "/element-package/base/button" },
        { text: "link", link: "/element-package/base/link" },
        { text: "space", link: "/element-package/base/space" },
        { text: "scrollbar", link: "/element-package/base/scrollbar" },
        { text: "config-provider", link: "/element-package/base/config-provider" },
      ],
    }
  ],
  '/element-package/form/': [
    {
      text: "form",
      items: [
        { text: "首页", link: "/element-package/form/" },
        { text: "一.cascader", link: "/element-package/form/1.cascader" },
        { text: "二.checkbox", link: "/element-package/form/2.checkbox" },
        { text: "三.input", link: "/element-package/form/3.input" },
        { text: "四.inputnumber", link: "/element-package/form/4.inputnumber" },
        { text: "五.select", link: "/element-package/form/5.select" },
        { text: "六.selectv2", link: "/element-package/form/6.selectv2" },
        { text: "七.radio", link: "/element-package/form/7.radio" },
        { text: "八.switch", link: "/element-package/form/8.switch" },
        { text: "九.slider", link: "/element-package/form/9.slider" },
        { text: "十.timepicker", link: "/element-package/form/10.timepicker" },
        { text: "十一.timeselect", link: "/element-package/form/11.timeselect" },
        { text: "十二.datepicker", link: "/element-package/form/12.datepicker" },
        { text: "十三.datetimepicker", link: "/element-package/form/13.datetimepicker" },
        { text: "十四.upload", link: "/element-package/form/14.upload" },
        { text: "十五.rate", link: "/element-package/form/15.rate" },
        { text: "十六.ColorPicker", link: "/element-package/form/16.colorpicker" },
        { text: "十七.Transfer", link: "/element-package/form/17.transfer" },
        { text: "十八.Form", link: "/element-package/form/18.form" },
      ],
    },
  ],
  '/element-package/data/': [
    {
      text: "data",
      items: [
        { text: "首页", link: "/element-package/data/" },
        { text: "table", link: "/element-package/data/table" },
        { text: "tag", link: "/element-package/data/tag" },
        { text: "progress", link: "/element-package/data/progress" },
        { text: "tree", link: "/element-package/data/tree" },
        { text: "pagination", link: "/element-package/data/pagination" },
        { text: "badge", link: "/element-package/data/badge" },
        { text: "avatar", link: "/element-package/data/avatar" },
        { text: "skeleton", link: "/element-package/data/skeleton" },
        { text: "empty", link: "/element-package/data/empty" },
        { text: "descriptions", link: "/element-package/data/descriptions" },
        { text: "result", link: "/element-package/data/result" },
      ],
    },
  ],
  '/element-package/notice/': [
    {
      text: "notice",
      items: [
        { text: "首页", link: "/element-package/notice/" },
        { text: "alert", link: "/element-package/notice/alert" },
        { text: "loading", link: "/element-package/notice/loading" },
        { text: "message", link: "/element-package/notice/message" },
        { text: "messagebox", link: "/element-package/notice/messagebox" },
        { text: "notification", link: "/element-package/notice/notification" },
      ],
    },
  ],
  '/element-package/navigation/': [
    {
      text: "navigation",
      items: [
        { text: "首页", link: "/element-package/navigation/" },
        { text: "affix", link: "/element-package/navigation/affix" },
        { text: "navmenu", link: "/element-package/navigation/navmenu" },
        { text: "tabs", link: "/element-package/navigation/tabs" },
        { text: "breadcrumb", link: "/element-package/navigation/breadcrumb" },
        { text: "pageheader", link: "/element-package/navigation/pageheader" },
        { text: "dropdown", link: "/element-package/navigation/dropdown" },
        { text: "steps", link: "/element-package/navigation/steps" },
      ],
    }
  ],
  '/element-package/others/': [
    {
      text: "others",
      items: [
        { text: "首页", link: "/element-package/others/" },
        { text: "dialog", link: "/element-package/others/dialog" },
        { text: "tooltip", link: "/element-package/others/tooltip" },
        { text: "popover", link: "/element-package/others/popover" },
        { text: "popconfirm", link: "/element-package/others/popconfirm" },
        { text: "card", link: "/element-package/others/card" },
        { text: "carousel", link: "/element-package/others/carousel" },
        { text: "collapse", link: "/element-package/others/collapse" },
        { text: "timeline", link: "/element-package/others/timeline" },
        { text: "drawer", link: "/element-package/others/drawer" },
        { text: "divider", link: "/element-package/others/divider" },
        { text: "calendar-calendar", link: "/element-package/others/calendar-calendar" },
        { text: "image", link: "/element-package/others/image" },
        { text: "backtop", link: "/element-package/others/backtop" },
        { text: "infinitescroll", link: "/element-package/others/infinitescroll" },
      ],
    },
  ]
}