export default {
  '/question/': [
    {
      text: "组件问题",
      items: [
        { text: "问题记录1", link: "/question/a/" },
      ],
    },
  ],
  '/element-plus/base/': [
    {
      text: "基础组件",
      items: [
        { text: "首页", link: "/element-plus/base/" },
        { text: "layout", link: "/element-plus/base/layout" },
        { text: "container", link: "/element-plus/base/container" },
        { text: "button", link: "/element-plus/base/button" },
        { text: "link", link: "/element-plus/base/link" },
        { text: "space", link: "/element-plus/base/space" },
        { text: "scrollbar", link: "/element-plus/base/scrollbar" },
        { text: "config-provider", link: "/element-plus/base/config-provider" },
      ],
    },
  ],
    '/element-plus/form/': [
    {
      text: "表单组件",
      items: [
        // { text: "index", link: "/element-plus/form/" },
        { text: "一.Cascader", link: "/element-plus/form/cascader" },
        { text: "二.Checkbox", link: "/element-plus/form/checkbox" },
        { text: "三.Input", link: "/element-plus/form/input" },
        { text: "四.InputNumber", link: "/element-plus/form/inputnumber" },
        { text: "五.Select", link: "/element-plus/form/select" },
        { text: "六.Select V2", link: "/element-plus/form/selectv2" },
        { text: "七.Radio", link: "/element-plus/form/radio" },
        { text: "八.Switch", link: "/element-plus/form/switch" },
        { text: "十七.Transfer", link: "/element-plus/form/slider" },
        { text: "十.TimePicker", link: "/element-plus/form/timepicker" },
        { text: "十一.TimeSelect", link: "/element-plus/form/timeselect" },
        { text: "十二.DatePicker", link: "/element-plus/form/datepicker" },
        { text: "十三.DateTimePicker", link: "/element-plus/form/datetimepicker" },
        { text: "十四.Upload", link: "/element-plus/form/upload" },
        { text: "十五.Rate", link: "/element-plus/form/rate" },
        { text: "十六.ColorPicker", link: "/element-plus/form/colorpicker" },
        { text: "十七.Transfer", link: "/element-plus/form/transfer" },
        { text: "十八.Form", link: "/element-plus/form/form" },
      ],
    },
  ],
  '/element-plus/data/': [
    {
      text: "数据展示",
      items: [
        // { text: "index", link: "/element-plus/data/" },
        { text: "table", link: "/element-plus/data/table" },
        { text: "tag", link: "/element-plus/data/tag" },
        { text: "progress", link: "/element-plus/data/progress" },
        { text: "tree", link: "/element-plus/data/tree" },
        { text: "pagination", link: "/element-plus/data/pagination" },
        { text: "badge", link: "/element-plus/data/badge" },
        { text: "avatar", link: "/element-plus/data/avatar" },
        { text: "skeleton", link: "/element-plus/data/skeleton" },
        { text: "empty", link: "/element-plus/data/empty" },
        { text: "descriptions", link: "/element-plus/data/descriptions" },
        { text: "result", link: "/element-plus/data/result" },
      ],
    },
  ],
  '/element-plus/notice/': [
    {
      text: "反馈组件",
      items: [
        // { text: "index", link: "/element-plus/notice/" },
        { text: "alert", link: "/element-plus/notice/alert" },
        { text: "loading", link: "/element-plus/notice/loading" },
        { text: "message", link: "/element-plus/notice/message" },
        { text: "messagebox", link: "/element-plus/notice/messagebox" },
        { text: "notification", link: "/element-plus/notice/notification" },
        { text: "tooltip", link: "/element-plus/notice/tooltip" },
      ],
    },
  ],
  '/element-plus/navigation/': [
    {
      text: "导航组件",
      items: [
        // { text: "index", link: "/element-plus/navigation/" },
        { text: "固钉", link: "/element-plus/navigation/affix" },
        { text: "navmenu", link: "/element-plus/navigation/navmenu" },
        { text: "标签页", link: "/element-plus/navigation/tabs" },
        { text: "面包屑", link: "/element-plus/navigation/breadcrumb" },
        { text: "页头", link: "/element-plus/navigation/pageheader" },
        { text: "下拉菜单", link: "/element-plus/navigation/dropdown" },
        { text: "步骤条", link: "/element-plus/navigation/steps" },
      ],
    },
  ],
  '/element-plus/others/': [
    {
      text: "其他组件",
      items: [
        // { text: "index", link: "/element-plus/others/" },
        { text: "dialog", link: "/element-plus/others/dialog" },
        { text: "tooltip", link: "/element-plus/others/tooltip" },
        { text: "popover", link: "/element-plus/others/popover" },
        { text: "popconfirm", link: "/element-plus/others/popconfirm" },
        { text: "card", link: "/element-plus/others/card" },
        { text: "carousel", link: "/element-plus/others/carousel" },
        { text: "collapse", link: "/element-plus/others/collapse" },
        { text: "timeline", link: "/element-plus/others/timeline" },
        { text: "drawer", link: "/element-plus/others/drawer" },
        { text: "divider", link: "/element-plus/others/divider" },
        { text: "calendar-calendar", link: "/element-plus/others/calendar-calendar" },
        { text: "image", link: "/element-plus/others/image" },
        { text: "backtop", link: "/element-plus/others/backtop" },
        { text: "infinitescroll", link: "/element-plus/others/infinitescroll" },
      ],
    },
  ],
  '/element-package/base/': [
    {
      text: "基础组件",
      items: [
        { text: "首页", link: "/element-package/base/" },
        { text: "layout", link: "/element-package/base/layout" },
        { text: "container", link: "/element-package/base/container" },
        { text: "button", link: "/element-package/base/button" },
        { text: "link", link: "/element-package/base/link" },
        { text: "space", link: "/element-package/base/space" },
        { text: "scrollbar", link: "/element-package/base/scrollbar" },
        { text: "config-provider", link: "/element-package/base/config-provider" },
      ],
    },
  ],
  '/element-package/form/': [
    {
      text: "表单组件",
      items: [
        { text: "index", link: "/element-package/form/" },
        { text: "一.级联选择", link: "/element-package/form/cascader" },
        { text: "二.多选器", link: "/element-package/form/checkbox" },
        { text: "三.输入框", link: "/element-package/form/input" },
        { text: "四.数字输入框", link: "/element-package/form/inputnumber" },
        { text: "五.选择器", link: "/element-package/form/select" },
        { text: "六.Select V2", link: "/element-package/form/selectv2" },
        { text: "七.Radio", link: "/element-package/form/radio" },
        { text: "八.开关", link: "/element-package/form/switch" },
        { text: "十七.Transfer", link: "/element-package/form/slider" },
        { text: "十.日期选择器", link: "/element-package/form/timepicker" },
        { text: "十一.时间选择", link: "/element-package/form/timeselect" },
        { text: "十二.日期时间选择器", link: "/element-package/form/datepicker" },
        { text: "十三.DateTimePicker", link: "/element-package/form/datetimepicker" },
        { text: "十四.上传", link: "/element-package/form/upload" },
        { text: "十五.Rate", link: "/element-package/form/rate" },
        { text: "十六.ColorPicker", link: "/element-package/form/colorpicker" },
        { text: "十七.Transfer", link: "/element-package/form/transfer" },
        { text: "十八.表单", link: "/element-package/form/form" },
      ],
    },
  ],
  '/element-package/data/': [
    {
      text: "数据展示",
      items: [
        // { text: "index", link: "/element-package/data/" },
        { text: "头像", link: "/element-package/data/avatar" },
        { text: "徽章", link: "/element-package/data/badge" },
        { text: "日历", link: "/element-package/data/calendar" },
        { text: "卡片", link: "/element-package/data/card" },
        { text: "走马灯", link: "/element-package/data/carousel" },
        { text: "折叠面板", link: "/element-package/data/collapse" },
        { text: "描述列表", link: "/element-package/data/descriptions" },
        { text: "空状态", link: "/element-package/data/empty" },
        { text: "表格", link: "/element-package/data/table" },
        { text: "标签", link: "/element-package/data/tag" },
        { text: "进度条", link: "/element-package/data/progress" },
        { text: "树形控件", link: "/element-package/data/tree" },
        { text: "分页", link: "/element-package/data/pagination" },
        { text: "骨架屏", link: "/element-package/data/skeleton" },
        { text: "结果", link: "/element-package/data/result" },
      ],
    },
  ],
  '/element-package/notice/': [
    {
      text: "反馈组件",
      items: [
        // { text: "index", link: "/element-package/notice/" },
        { text: "alert", link: "/element-package/notice/alert" },
        { text: "loading", link: "/element-package/notice/loading" },
        { text: "message", link: "/element-package/notice/message" },
        { text: "messagebox", link: "/element-package/notice/messagebox" },
        { text: "notification", link: "/element-package/notice/notification" },
        { text: "tooltip", link: "/element-package/notice/tooltip" },
      ],
    },
  ],
  '/element-package/navigation/': [
    {
      text: "导航组件",
      items: [
        // { text: "index", link: "/element-package/navigation/" },
        { text: "affix", link: "/element-package/navigation/affix" },
        { text: "navmenu", link: "/element-package/navigation/navmenu" },
        { text: "tabs", link: "/element-package/navigation/tabs" },
        { text: "breadcrumb", link: "/element-package/navigation/breadcrumb" },
        { text: "pageheader", link: "/element-package/navigation/pageheader" },
        { text: "dropdown", link: "/element-package/navigation/dropdown" },
        { text: "steps", link: "/element-package/navigation/steps" },
      ],
    },
  ],
  '/element-package/others/': [
    {
      text: "其他组件",
      items: [
        // { text: "index", link: "/element-package/others/" },
        { text: "一.弹框组件", link: "/element-package/others/dialog" },
        { text: "tooltip", link: "/element-package/others/tooltip" },
        { text: "popover", link: "/element-package/others/popover" },
        { text: "popconfirm", link: "/element-package/others/popconfirm" },
        { text: "timeline", link: "/element-package/others/timeline" },
        { text: "十四.抽屉组件", link: "/element-package/others/drawer" },
        { text: "divider", link: "/element-package/others/divider" },
        { text: "calendar-calendar", link: "/element-package/others/calendar-calendar" },
        { text: "image", link: "/element-package/others/image" },
        { text: "backtop", link: "/element-package/others/backtop" },
        { text: "infinitescroll", link: "/element-package/others/infinitescroll" },
      ],
    },
  ],
  '/template/': [
    {
      text: "页面模板",
      items: [
        { text: "页面模板1", link: "/template/page1/" },
      ],
    },
  ],
}